/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  PasaPayBatchRouter,
  PasaPayBatchRouterInterface,
} from "../../PasaPayBatchRouter.sol/PasaPayBatchRouter";

const _abi = [
  {
    inputs: [],
    name: "EmptyBatch",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidLength",
    type: "error",
  },
  {
    inputs: [],
    name: "TransferFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "ZeroAddress",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "address[]",
        name: "recipients",
        type: "address[]",
      },
      {
        internalType: "uint256[]",
        name: "amounts",
        type: "uint256[]",
      },
    ],
    name: "batchTransferERC20",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5061038f806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c806379f2447e14610030575b600080fd5b61004361003e366004610257565b610045565b005b6001600160a01b03851661006c5760405163d92e233d60e01b815260040160405180910390fd5b82600081900361008f5760405163c2e5347d60e01b815260040160405180910390fd5b8082146100af5760405163251f56a160e21b815260040160405180910390fd5b60005b818110156101e65760008686838181106100ce576100ce6102d8565b90506020020160208101906100e391906102ee565b90506001600160a01b03811661010c5760405163d92e233d60e01b815260040160405180910390fd5b6000858584818110610120576101206102d8565b90506020020135905060008111156101d1576040516323b872dd60e01b81523360048201526001600160a01b03838116602483015260448201839052600091908b16906323b872dd906064016020604051808303816000875af115801561018b573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906101af9190610310565b9050806101cf576040516312171d8360e31b815260040160405180910390fd5b505b505080806101de90610332565b9150506100b2565b50505050505050565b80356001600160a01b038116811461020657600080fd5b919050565b60008083601f84011261021d57600080fd5b50813567ffffffffffffffff81111561023557600080fd5b6020830191508360208260051b850101111561025057600080fd5b9250929050565b60008060008060006060868803121561026f57600080fd5b610278866101ef565b9450602086013567ffffffffffffffff8082111561029557600080fd5b6102a189838a0161020b565b909650945060408801359150808211156102ba57600080fd5b506102c78882890161020b565b969995985093965092949392505050565b634e487b7160e01b600052603260045260246000fd5b60006020828403121561030057600080fd5b610309826101ef565b9392505050565b60006020828403121561032257600080fd5b8151801515811461030957600080fd5b60006001820161035257634e487b7160e01b600052601160045260246000fd5b506001019056fea26469706673582212208806a014a14ebf428df14fe156f5d1a2f66ef8073ca0ddaf73990d1cfbb4d2e364736f6c63430008140033";

type PasaPayBatchRouterConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: PasaPayBatchRouterConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class PasaPayBatchRouter__factory extends ContractFactory {
  constructor(...args: PasaPayBatchRouterConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      PasaPayBatchRouter & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): PasaPayBatchRouter__factory {
    return super.connect(runner) as PasaPayBatchRouter__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PasaPayBatchRouterInterface {
    return new Interface(_abi) as PasaPayBatchRouterInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): PasaPayBatchRouter {
    return new Contract(address, _abi, runner) as unknown as PasaPayBatchRouter;
  }
}
